name = "effland-website"
compatibility_date = "2023-07-10"
compatibility_flags = ["nodejs_compat"]

[vars]
# You can add variables here if needed, but not secrets
# For secrets like DATABASE_URL, use the Cloudflare dashboard

# The following line tells Cloudflare where to find your built files
# But only if you need a different location than the project root
# pages_build_output_dir = "dist"